name             'chef-jepsen'
maintainer       'Justin Alan Ryan'
maintainer_email 'bitmonk@icloud.com'
license          'Apache 2.0'
description      'Installs/Configures chef-jepsen'
long_description 'Installs/Configures chef-jepsen'
version          '0.1.0'
